namespace synonym_server
{
  public static class Stems
  {
    public static readonly List<(string word, string partOfSpeech)> Words = new List<(string word, string partOfSpeech)>
{
    ("About", "preposition"), ("After", "preposition"), ("Again", "adverb"), ("Against", "preposition"),
    ("Almost", "adverb"), ("Always", "adverb"), ("Among", "preposition"), ("Animal", "noun"),
    ("Another", "determiner"), ("Answer", "verb"), ("Around", "adverb"), ("Arrange", "verb"),
    ("Arrive", "verb"), ("Article", "noun"), ("Artist", "noun"), ("Asleep", "adjective"),
    ("Assert", "verb"), ("Attend", "verb"), ("August", "adjective"), ("Average", "adjective"),
    ("Balcony", "noun"), ("Battery", "noun"), ("Believe", "verb"), ("Beneath", "preposition"),
    ("Bicycle", "noun"), ("Blanket", "noun"), ("Breathe", "verb"), ("Briefly", "adverb"),
    ("Brother", "noun"), ("Burglar", "noun"), ("Butterfly", "noun"), ("Calendar", "noun"),
    ("Campaign", "noun"), ("Capable", "adjective"), ("Carpet", "noun"), ("Carry", "verb"),
    ("Central", "adjective"), ("Chamber", "noun"), ("Chapter", "noun"), ("Charity", "noun"),
    ("Cheerful", "adjective"), ("Chemist", "noun"), ("Climber", "noun"), ("Closely", "adverb"),
    ("Clothes", "noun"), ("Coffee", "noun"), ("Comment", "noun"), ("Company", "noun"),
    ("Compere", "noun"), ("Consider", "verb"), ("Control", "verb"), ("Corner", "noun"),
    ("Council", "noun"), ("Country", "noun"), ("Couple", "noun"), ("Courage", "noun"),
    ("Create", "verb"), ("Criminal", "noun"), ("Critics", "noun"), ("Cultural", "adjective"),
    ("Current", "adjective"), ("Cutting", "noun"), ("Dancing", "noun"), ("Debater", "noun"),
    ("Delight", "noun"), ("Deliver", "verb"), ("Demand", "noun"), ("Deposit", "verb"),
    ("Deserve", "verb"), ("Designer", "noun"), ("Determine", "verb"), ("Develop", "verb"),
    ("Devilish", "adjective"), ("Diamond", "noun"), ("Difficult", "adjective"), ("Diligent", "adjective"),
    ("Disagree", "verb"), ("Discover", "verb"), ("Discuss", "verb"), ("Dislike", "verb"),
    ("Divorce", "noun"), ("Domestic", "adjective"), ("Donkey", "noun"), ("Dramatic", "adjective"),
    ("Durable", "adjective"), ("Dweller", "noun"), ("Eagerly", "adverb"), ("Earring", "noun"),
    ("Eastern", "adjective"), ("Economy", "noun"), ("Educate", "verb"), ("Efficient", "adjective"),
    ("Elastic", "adjective"), ("Electric", "adjective"), ("Elegant", "adjective"), ("Embassy", "noun"),
    ("Embrace", "verb"), ("Employee", "noun"), ("Enormous", "adjective"), ("Enthusiast", "noun"), ("Equal", "adjective"),
("Escape", "verb"), ("Essential", "adjective"), ("Eternal", "adjective"), ("Evaluate", "verb"),
("Evidence", "noun"), ("Exactly", "adverb"), ("Examine", "verb"), ("Excellent", "adjective"),
("Exciting", "adjective"), ("Executive", "noun"), ("Exercise", "noun"), ("Exhibition", "noun"),
("Existence", "noun"), ("Expand", "verb"), ("Expensive", "adjective"), ("Expert", "noun"),
("Explore", "verb"), ("Express", "verb"), ("Extra", "adjective"), ("Extreme", "adjective"),
("Eyebrow", "noun"), ("Fabric", "noun"), ("Familiar", "adjective"), ("Family", "noun"),
("Famous", "adjective"), ("Fantasy", "noun"), ("Fashion", "noun"), ("Festival", "noun"),
("Fever", "noun"), ("Fiction", "noun"), ("Fighting", "noun"), ("Financial", "adjective"),
("Fine", "adjective"), ("Finger", "noun"), ("Finish", "verb"), ("Firefighter", "noun"),
("Fitness", "noun"), ("Flower", "noun"), ("Focus", "noun"), ("Football", "noun"),
("Foreign", "adjective"), ("Forest", "noun"), ("Forgive", "verb"), ("Formal", "adjective"),
("Fortune", "noun"), ("Forward", "adverb"), ("Foundation", "noun"), ("Freedom", "noun"),
("Frequency", "noun"), ("Friendly", "adjective"), ("Fruit", "noun"), ("Fun", "noun"),
("Function", "noun"), ("Fundamental", "adjective"), ("Furniture", "noun"), ("Gallery", "noun"),
("Game", "noun"), ("Garage", "noun"), ("Garden", "noun"), ("Gather", "verb"),
("General", "adjective"), ("Generate", "verb"), ("Generation", "noun"), ("Genuine", "adjective"),
("Geography", "noun"), ("Gesture", "noun"), ("Get", "verb"), ("Gift", "noun"),
("Giraffe", "noun"), ("Girl", "noun"), ("Give", "verb"), ("Glamorous", "adjective"),
("Glorious", "adjective"), ("Gloves", "noun"), ("Go", "verb"), ("Goddess", "noun"),
("Gold", "noun"), ("Good", "adjective"), ("Government", "noun"), ("Graceful", "adjective"),
("Graduate", "verb"), ("Grass", "noun"), ("Great", "adjective"), ("Green", "adjective"),
("Greet", "verb"), ("Grey", "adjective"), ("Ground", "noun"), ("Group", "noun"),
("Grow", "verb"), ("Growth", "noun"), ("Guard", "noun"), ("Guess", "verb"),
("Guide", "noun"), ("Guilty", "adjective"), ("Guitar", "noun"), ("Gun", "noun"),
("Hair", "noun"), ("Half", "determiner"), ("Hall", "noun"), ("Hand", "noun"),
("Handle", "verb"), ("Hang", "verb"), ("Happen", "verb"), ("Happy", "adjective"),
("Harbour", "noun"),("Hard", "adjective"), ("Harm", "noun"), ("Harmony", "noun"), ("Hat", "noun"),
("Have", "verb"), ("Head", "noun"), ("Heal", "verb"), ("Health", "noun"),
("Healthy", "adjective"), ("Hear", "verb"), ("Heart", "noun"), ("Heaven", "noun"),
("Heavy", "adjective"), ("Height", "noun"), ("Help", "verb"), ("High", "adjective"),
("Highlight", "verb"), ("Hill", "noun"), ("Hire", "verb"), ("Historical", "adjective"),
("History", "noun"), ("Hobby", "noun"), ("Hold", "verb"), ("Holiday", "noun"),
("Home", "noun"), ("Honest", "adjective"), ("Honey", "noun"), ("Hope", "noun"),
("Horror", "noun"), ("Horse", "noun"), ("Hospital", "noun"), ("Host", "noun"),
("Hot", "adjective"), ("Hotel", "noun"), ("Hour", "noun"), ("House", "noun"),
("Hover", "verb"), ("How", "adverb"), ("Human", "adjective"), ("Humorous", "adjective"),
("Hunt", "verb"), ("Hurry", "verb"), ("Hurt", "verb"), ("Ice", "noun"),
("Idea", "noun"), ("Identify", "verb"), ("Identity", "noun"), ("Idle", "adjective"),
("If", "conjunction"), ("Ignore", "verb"), ("Ill", "adjective"), ("Illegal", "adjective"),
("Illusion", "noun"), ("Image", "noun"), ("Imagine", "verb"), ("Immediate", "adjective"),
("Immune", "adjective"), ("Impact", "noun"), ("Implement", "verb"), ("Impose", "verb"),
("Impress", "verb"), ("Improve", "verb"), ("In", "preposition"), ("Incentive", "noun"),
("Incident", "noun"), ("Include", "verb"), ("Income", "noun"), ("Increase", "verb"),
("Independence", "noun"), ("Index", "noun"), ("Indian", "adjective"), ("Indicate", "verb"),
("Individual", "noun"), ("Indoor", "adjective"), ("Industry", "noun"), ("Infant", "noun"),
("Infect", "verb"), ("Influence", "verb"), ("Inform", "verb"), ("Information", "noun"),
("Ingredient", "noun"), ("Initial", "adjective"), ("Initiative", "noun"), ("Inject", "verb"),
("Injure", "verb"), ("Injury", "noun"), ("Ink", "noun"), ("Inner", "adjective"),
("Innocent", "adjective"), ("Innovate", "verb"), ("Input", "noun"), ("Inquiry", "noun"),
("Insect", "noun"), ("Insert", "verb"), ("Inside", "adverb"), ("Insight", "noun"),
("Inspire", "verb"), ("Install", "verb"), ("Instance", "noun"), ("Instant", "adjective"),
("Instead", "adverb"), ("Instruction", "noun"), ("Instrument", "noun"), ("Insurance", "noun"),
("Integrate", "verb"), ("Intellectual", "adjective"), ("Intelligence", "noun"), ("Intend", "verb"),
("Intense", "adjective"), ("Interact", "verb"), ("Interest", "noun"), ("Interior", "noun"), ("International", "adjective"), ("Internet", "noun"),
("Interpret", "verb"), ("Interrupt", "verb"), ("Interval", "noun"), ("Interview", "noun"),
("Introduce", "verb"), ("Invent", "verb"), ("Invest", "verb"), ("Investigate", "verb"),
("Involve", "verb"), ("Iron", "noun"), ("Island", "noun"), ("Isolate", "verb"),
("Issue", "noun"), ("It", "pronoun"), ("Item", "noun"), ("Jacket", "noun"),
("Jam", "noun"), ("January", "noun"), ("Jealous", "adjective"), ("Jet", "noun"),
("Jewelry", "noun"), ("Job", "noun"), ("Join", "verb"), ("Joint", "adjective"),
("Joke", "noun"), ("Journal", "noun"), ("Journey", "noun"), ("Joy", "noun"),
("Judge", "noun"), ("Judgment", "noun"), ("Juggle", "verb"), ("Juice", "noun"),
("July", "noun"), ("Jump", "verb"), ("June", "noun"), ("Junior", "adjective"),
("Jury", "noun"), ("Just", "adjective"), ("Justice", "noun"), ("Juvenile", "adjective"),
("Keep", "verb"), ("Key", "noun"), ("Kick", "verb"), ("Kid", "noun"),
("Kidnap", "verb"), ("Kill", "verb"), ("Kind", "adjective"), ("King", "noun"),
("Kiss", "verb"), ("Kitchen", "noun"), ("Knee", "noun"), ("Knife", "noun"),
("Knock", "verb"), ("Know", "verb"), ("Knowledge", "noun"), ("Lab", "noun"),
("Label", "noun"), ("Laboratory", "noun"), ("Lack", "noun"), ("Ladder", "noun"),
("Lady", "noun"), ("Lake", "noun"), ("Lamp", "noun"), ("Land", "noun"),
("Language", "noun"), ("Laptop", "noun"), ("Large", "adjective"), ("Last", "adjective"),
("Late", "adjective"), ("Laugh", "verb"), ("Launch", "verb"), ("Law", "noun"),
("Lawn", "noun"), ("Lawyer", "noun"), ("Lay", "verb"), ("Lazy", "adjective"),
("Lead", "verb"), ("Leader", "noun"), ("Leadership", "noun"), ("Leaf", "noun"),
("League", "noun"), ("Lean", "verb"), ("Learn", "verb"), ("Lease", "verb"),
("Leather", "noun"), ("Leave", "verb"), ("Lecture", "noun"), ("Left", "adjective"),
("Legal", "adjective"), ("Legend", "noun"), ("Legislation", "noun"), ("Legitimate", "adjective"),
("Lend", "verb"), ("Length", "noun"), ("Less", "adjective"), ("Lesson", "noun"),
("Let", "verb"), ("Letter", "noun"), ("Level", "noun"), ("Liar", "noun"),
("Liberal", "adjective"), ("Library", "noun"), ("License", "noun"), ("Lie", "verb"),
("Life", "noun"), ("Lift", "verb"), ("Light", "noun"), ("Like", "preposition"),
("Limit", "noun"), ("Line", "noun"), ("Linen", "noun"), ("Link", "noun"), ("Lip", "noun"), ("Liquid", "adjective"),
("List", "noun"), ("Listen", "verb"), ("Literature", "noun"), ("Little", "adjective"),
("Live", "verb"), ("Lively", "adjective"), ("Living", "adjective"), ("Load", "noun"),
("Loan", "noun"), ("Lobby", "noun"), ("Local", "adjective"), ("Locate", "verb"),
("Location", "noun"), ("Lock", "noun"), ("Log", "noun"), ("Logic", "noun"),
("Lonely", "adjective"), ("Long", "adjective"), ("Look", "verb"), ("Loop", "noun"),
("Loose", "adjective"), ("Lord", "noun"), ("Lose", "verb"), ("Loss", "noun"),
("Lot", "noun"), ("Loud", "adjective"), ("Love", "noun"), ("Lovely", "adjective"),
("Low", "adjective"), ("Lower", "adjective"), ("Luck", "noun"), ("Lucky", "adjective"),
("Luggage", "noun"), ("Lumber", "noun"), ("Lunch", "noun"), ("Luxury", "noun"),
("Machine", "noun"), ("Mad", "adjective"), ("Magazine", "noun"), ("Mail", "noun"),
("Main", "adjective"), ("Mainstream", "adjective"), ("Maintain", "verb"), ("Major", "adjective"),
("Majority", "noun"), ("Make", "verb"), ("Male", "adjective"), ("Mall", "noun"),
("Man", "noun"), ("Manage", "verb"), ("Management", "noun"), ("Manager", "noun"),
("Manner", "noun"), ("Manual", "adjective"), ("Manufacture", "verb"), ("Manufacturer", "noun"),
("Many", "adjective"), ("Map", "noun"), ("March", "verb"), ("Margin", "noun"),
("Mark", "noun"), ("Market", "noun"), ("Marriage", "noun"), ("Marry", "verb"),
("Mask", "noun"), ("Mass", "noun"), ("Master", "noun"), ("Match", "verb"),
("Mate", "noun"), ("Material", "noun"), ("Mathematics", "noun"), ("Matter", "noun"),
("May", "modal verb"), ("Maybe", "adverb"), ("Mayor", "noun"), ("Meal", "noun"),
("Mean", "verb"), ("Meaning", "noun"), ("Means", "noun"), ("Measure", "verb"),
("Measurement", "noun"), ("Meat", "noun"), ("Mechanism", "noun"), ("Media", "noun"),
("Medical", "adjective"), ("Medicine", "noun"), ("Medium", "adjective"), ("Meet", "verb"),
("Meeting", "noun"), ("Member", "noun"), ("Membership", "noun"), ("Memory", "noun"),
("Mental", "adjective"), ("Mention", "verb"), ("Menu", "noun"), ("Merchant", "noun"),
("Mere", "adjective"), ("Merge", "verb"), ("Merit", "noun"), ("Message", "noun"),
("Metal", "noun"), ("Method", "noun"), ("Mexican", "adjective"), ("Microphone", "noun"),
("Middle", "adjective"), ("Midnight", "noun"), ("Might", "modal verb"), ("Mild", "adjective"), ("Mile", "noun"), ("Military", "adjective"), ("Milk", "noun"), ("Million", "noun"),
("Mind", "noun"), ("Mine", "pronoun"), ("Mineral", "noun"), ("Minimum", "adjective"),
("Minister", "noun"), ("Ministry", "noun"), ("Minor", "adjective"), ("Minority", "noun"),
("Minute", "noun"), ("Mirror", "noun"), ("Miss", "verb"), ("Mission", "noun"), ("Mistake", "noun"),
("Mix", "verb"), ("Mixture", "noun"), ("Mobile", "adjective"), ("Mode", "noun"),
("Model", "noun"), ("Moderate", "adjective"), ("Modern", "adjective"), ("Modest", "adjective"),
("Moment", "noun"), ("Money", "noun"), ("Monitor", "verb"), ("Month", "noun"),
("Mood", "noun"), ("Moon", "noun"), ("Moral", "adjective"), ("More", "adverb"),
("Morning", "noun"), ("Mortgage", "noun"), ("Most", "adjective"), ("Mostly", "adverb"),
("Mother", "noun"), ("Motion", "noun"), ("Motivation", "noun"), ("Motor", "noun"),
("Mount", "verb"), ("Mountain", "noun"), ("Mouse", "noun"), ("Mouth", "noun"),
("Move", "verb"), ("Movement", "noun"), ("Movie", "noun"), ("Much", "adverb"),
("Mud", "noun"), ("Multimedia", "noun"), ("Multiple", "adjective"), ("Municipal", "adjective"),
("Murder", "noun"), ("Muscle", "noun"), ("Museum", "noun"), ("Music", "noun"),
("Musical", "adjective"), ("Musician", "noun"), ("Muslim", "adjective"), ("Must", "verb"),
("Mutual", "adjective"), ("Myself", "pronoun"), ("Mystery", "noun"), ("Naked", "adjective"),
("Name", "noun"), ("Narrative", "noun"), ("Narrow", "adjective"), ("Nation", "noun"),
("National", "adjective"), ("Native", "adjective"), ("Natural", "adjective"), ("Nature", "noun"),
("Naval", "adjective"), ("Near", "adverb"), ("Nearby", "adverb"), ("Nearly", "adverb"),
("Necessarily", "adverb"), ("Necessary", "adjective"), ("Neck", "noun"), ("Need", "noun"),
("Negative", "adjective"), ("Negotiate", "verb"), ("Negotiation", "noun"), ("Neighbor", "noun"),
("Neither", "adverb"), ("Nerve", "noun"), ("Nervous", "adjective"), ("Net", "noun"),
("Network", "noun"), ("Never", "adverb"), ("Nevertheless", "conjunction"), ("New", "adjective"),
("Newly", "adverb"), ("News", "noun"), ("Newspaper", "noun"), ("Next", "adjective"),
("Nice", "adjective"), ("Night", "noun"), ("No", "adverb"), ("Nobody", "pronoun"),
("Nod", "verb"), ("Noise", "noun"), ("Nomination", "noun"), ("None", "pronoun"),
("Nonetheless", "adverb"), ("Nonsense", "noun"), ("Noon", "noun"), ("Norm", "noun"),
("Normal", "adjective"), ("North", "noun"), ("Northeast", "noun"), ("Northern", "adjective"),
("Northwest", "noun"), ("Nose", "noun"), ("Not", "adverb"), ("Note", "noun"),
("Notebook", "noun"), ("Nothing", "pronoun"), ("Notice", "verb"), ("Notification", "noun"),("Notion", "noun"), ("Now", "adverb"), ("Nowadays", "adverb"), ("Nuclear", "adjective"),
("Number", "noun"), ("Numerous", "adjective"), ("Nurse", "noun"), ("Nutrition", "noun"),
("Object", "noun"), ("Objective", "adjective"), ("Obligation", "noun"), ("Observation", "noun"),
("Observe", "verb"), ("Obvious", "adjective"), ("Obviously", "adverb"), ("Occasion", "noun"),
("Occur", "verb"), ("Ocean", "noun"), ("Odd", "adjective"), ("Odds", "noun"),
("Of", "preposition"), ("Off", "adverb"), ("Offense", "noun"), ("Offensive", "adjective"),
("Offer", "verb"), ("Office", "noun"), ("Officer", "noun"), ("Official", "adjective"),
("Often", "adverb"), ("Oh", "interjection"), ("Oil", "noun"), ("Ok", "adjective"),
("Old", "adjective"), ("Olympic", "adjective"), ("On", "preposition"), ("Once", "adverb"),
("One", "pronoun"), ("Oneself", "pronoun"), ("Onion", "noun"), ("Online", "adjective"),
("Only", "adverb"), ("Onto", "preposition"), ("Open", "adjective"), ("Opening", "noun"),
("Operate", "verb"), ("Operation", "noun"), ("Operator", "noun"), ("Opinion", "noun"),
("Opportunity", "noun"), ("Oppose", "verb"), ("Opposite", "adjective"), ("Opposition", "noun"),
("Option", "noun"), ("Or", "conjunction"), ("Orange", "adjective"), ("Order", "noun"),
("Ordinary", "adjective"), ("Organic", "adjective"), ("Organization", "noun"), ("Organize", "verb"),
("Orientation", "noun"), ("Origin", "noun"), ("Original", "adjective"), ("Originally", "adverb"),
("Other", "adjective"), ("Others", "pronoun"), ("Otherwise", "adverb"), ("Ought", "verb"),
("Our", "pronoun"), ("Ourselves", "pronoun"), ("Out", "adverb"), ("Outcome", "noun"),
("Outside", "adjective"), ("Oven", "noun"), ("Over", "preposition"), ("Overall", "adjective"),
("Overcome", "verb"), ("Overlook", "verb"), ("Owe", "verb"), ("Own", "verb"),
("Owner", "noun"), ("Oxygen", "noun"), ("Pace", "noun"), ("Pack", "verb"),
("Package", "noun"), ("Page", "noun"), ("Pain", "noun"), ("Paint", "verb"),
("Painter", "noun"), ("Painting", "noun"), ("Pair", "noun"), ("Pale", "adjective"),
("Palestinian", "adjective"), ("Palm", "noun"), ("Pan", "noun"), ("Panel", "noun"),
("Pant", "verb"), ("Paper", "noun"), ("Parent", "noun"), ("Parental", "adjective"),
("Parliament", "noun"), ("Part", "noun"), ("Participant", "noun"), ("Participate", "verb"),
("Participation", "noun"), ("Particular", "adjective"), ("Particularly", "adverb"), ("Partnership", "noun"), ("Party", "noun"), ("Pass", "verb"), ("Passage", "noun"),
("Passenger", "noun"), ("Passion", "noun"), ("Past", "adjective"), ("Pat", "verb"),
("Patch", "noun"), ("Path", "noun"), ("Patient", "adjective"), ("Patient", "noun"),
("Pattern", "noun"), ("Pause", "noun"), ("Pay", "verb"), ("Payment", "noun"),
("Peace", "noun"), ("Peak", "noun"), ("Peer", "noun"), ("Penalty", "noun"),
("People", "noun"), ("Pepper", "noun"), ("Per", "preposition"), ("Perceive", "verb"),
("Percentage", "noun"), ("Perception", "noun"), ("Perfect", "adjective"), ("Perfectly", "adverb"),
("Perform", "verb"), ("Performance", "noun"), ("Perhaps", "adverb"), ("Period", "noun"),
("Permanent", "adjective"), ("Permission", "noun"), ("Permit", "verb"), ("Person", "noun"),
("Personal", "adjective"), ("Personality", "noun"), ("Personally", "adverb"), ("Personnel", "noun"),
("Perspective", "noun"), ("Persuade", "verb"), ("Pet", "noun"), ("Phase", "noun"),
("Philosophy", "noun"), ("Phone", "noun"), ("Photo", "noun"), ("Photograph", "verb"),
("Photographer", "noun"), ("Photography", "noun"), ("Phrase", "noun"), ("Physical", "adjective"),
("Physically", "adverb"), ("Physician", "noun"), ("Physics", "noun"), ("Piano", "noun"),
("Pick", "verb"), ("Picture", "noun"), ("Pie", "noun"), ("Piece", "noun"),
("Pile", "noun"), ("Pilot", "noun"), ("Pin", "noun"), ("Pipe", "noun"),
("Pitch", "noun"), ("Place", "noun"), ("Plan", "noun"), ("Plane", "noun"),
("Planet", "noun"), ("Planning", "noun"), ("Plant", "noun"), ("Plastic", "adjective"),
("Plate", "noun"), ("Platform", "noun"), ("Play", "verb"), ("Player", "noun"),
("Please", "verb"), ("Pleasure", "noun"), ("Plenty", "pronoun"), ("Plot", "noun"),
("Plus", "preposition"), ("PM", "noun"), ("Pocket", "noun"), ("Poem", "noun"),
("Poet", "noun"), ("Poetry", "noun"), ("Point", "noun"), ("Police", "noun"),
("Policy", "noun"), ("Political", "adjective"), ("Politics", "noun"), ("Poll", "noun"),
("Pollution", "noun"), ("Pool", "noun"), ("Poor", "adjective"), ("Pop", "noun"),
("Popular", "adjective"), ("Population", "noun"), ("Por", "preposition"), ("Port", "noun"),
("Portfolio", "noun"), ("Portray", "verb"), ("Pose", "verb"), ("Position", "noun"),
("Positive", "adjective"), ("Possess", "verb"), ("Possibility", "noun"), ("Possible", "adjective"),
("Possibly", "adverb"), ("Post", "noun"), ("Pot", "noun"), ("Potato", "noun"),
("Potential", "adjective"), ("Potential", "noun"), ("Pound", "noun"), ("Pour", "verb"), ("Poverty", "noun"),
("Powder", "noun"), ("Power", "noun"), ("Powerful", "adjective"), ("Practical", "adjective"),
("Practice", "noun"), ("Pray", "verb"), ("Prayer", "noun"), ("Preach", "verb"),
("Precisely", "adverb"), ("Predict", "verb"), ("Prediction", "noun"), ("Preference", "noun"),
("Preferred", "adjective"), ("Pregnancy", "noun"), ("Pregnant", "adjective"), ("Preparation", "noun"),
("Prepare", "verb"), ("Prescription", "noun"), ("Presence", "noun"), ("Present", "adjective"),
("Present", "verb"), ("Presentation", "noun"), ("Preserve", "verb"), ("President", "noun"),
("Press", "noun"), ("Pressure", "noun"), ("Pretend", "verb"), ("Pretty", "adjective"),
("Prevent", "verb"), ("Previous", "adjective"), ("Previously", "adverb"), ("Price", "noun"),
("Pride", "noun"), ("Priest", "noun"), ("Primarily", "adverb"), ("Primary", "adjective"),
("Prime", "adjective"), ("Prince", "noun"), ("Princess", "noun"), ("Principal", "adjective"),
("Principal", "noun"), ("Principle", "noun"), ("Print", "verb"), ("Prior", "adjective"),
("Priority", "noun"), ("Prison", "noun"), ("Prisoner", "noun"), ("Privacy", "noun"),
("Private", "adjective"), ("Probably", "adverb"), ("Problem", "noun"), ("Procedure", "noun"),
("Proceed", "verb"), ("Process", "noun"), ("Produce", "verb"), ("Producer", "noun"),
("Product", "noun"), ("Production", "noun"), ("Productive", "adjective"), ("Profession", "noun"),
("Professional", "adjective"), ("Professor", "noun"), ("Profile", "noun"), ("Profit", "noun"),
("Program", "noun"), ("Program", "verb"), ("Progress", "noun"), ("Project", "noun"),
("Promise", "verb"), ("Promise", "noun"), ("Promote", "verb"), ("Promotion", "noun"),
("Prompt", "verb"), ("Proof", "noun"), ("Proper", "adjective"), ("Properly", "adverb"),
("Property", "noun"), ("Proportion", "noun"), ("Proposal", "noun"), ("Propose", "verb"),
("Proposition", "noun"), ("Prosecutor", "noun"), ("Prospect", "noun"), ("Protect", "verb"),
("Protection", "noun"), ("Protein", "noun"), ("Protest", "noun"), ("Protest", "verb"),
("Proud", "adjective"), ("Prove", "verb"), ("Provide", "verb"), ("Provided", "conjunction"),
("Provider", "noun"), ("Province", "noun"), ("Provision", "noun"), ("Psychological", "adjective"),
("Psychology", "noun"), ("Public", "adjective"), ("Publication", "noun"), ("Publicity", "noun"),
("Publish", "verb"), ("Publisher", "noun"), ("Pull", "verb"), ("Pulse", "noun"),
("Pump", "noun"), ("Punch", "verb"), ("Punish", "verb"), ("Punishment", "noun"), ("Purchase", "verb"), ("Purchase", "noun"),
("Pure", "adjective"), ("Purely", "adverb"), ("Purple", "adjective"), ("Purpose", "noun"),
("Purse", "noun"), ("Pursue", "verb"), ("Push", "verb"), ("Put", "verb"),
("Qualify", "verb"), ("Quality", "noun"), ("Quantity", "noun"), ("Quarter", "noun"),
("Queen", "noun"), ("Question", "noun"), ("Question", "verb"), ("Quick", "adjective"),
("Quickly", "adverb"), ("Quiet", "adjective"), ("Quietly", "adverb"), ("Quit", "verb"),
("Quite", "adverb"), ("Quote", "verb"), ("Race", "noun"), ("Race", "verb"),
("Racism", "noun"), ("Racist", "noun"), ("Racist", "adjective"), ("Rack", "noun"),
("Radar", "noun"), ("Radiation", "noun"), ("Radical", "adjective"), ("Radio", "noun"),
("Rail", "noun"), ("Railroad", "noun"), ("Rain", "noun"), ("Raise", "verb"),
("Range", "noun"), ("Rank", "noun"), ("Rapid", "adjective"), ("Rapidly", "adverb"),
("Rare", "adjective"), ("Rarely", "adverb"), ("Rat", "noun"), ("Rate", "noun"),
("Rate", "verb"), ("Rather", "adverb"), ("Rating", "noun"), ("Ratio", "noun"),
("Raw", "adjective"), ("Reach", "verb"), ("React", "verb"), ("Reaction", "noun"),
("Read", "verb"), ("Reader", "noun"), ("Readily", "adverb"), ("Reading", "noun"),
("Ready", "adjective"), ("Real", "adjective"), ("Realistic", "adjective"), ("Reality", "noun"),
("Realize", "verb"), ("Really", "adverb"), ("Reason", "noun"), ("Reasonable", "adjective"),
("Rebel", "noun"), ("Rebel", "verb"), ("Rebellion", "noun"), ("Recall", "verb"),
("Receipt", "noun"), ("Receive", "verb"), ("Receiver", "noun"), ("Recent", "adjective"),
("Recently", "adverb"), ("Reception", "noun"), ("Recipe", "noun"), ("Recognition", "noun"),
("Recognize", "verb"), ("Recommend", "verb"), ("Recommendation", "noun"), ("Record", "noun"),
("Record", "verb"), ("Recording", "noun"), ("Recover", "verb"), ("Recovery", "noun"),
("Recruit", "verb"), ("Red", "adjective"), ("Reduce", "verb"), ("Reduction", "noun"),
("Refer", "verb"), ("Reference", "noun"), ("Reflect", "verb"), ("Reflection", "noun"),
("Reform", "noun"), ("Reform", "verb"), ("Refrigerator", "noun"), ("Refuse", "verb"),
("Regarding", "preposition"), ("Regard", "noun"), ("Regard", "verb"), ("Regret", "noun"),
("Regret", "verb"), ("Regular", "adjective"), ("Regularly", "adverb"), ("Regulation", "noun"),
("Reinforce", "verb"), ("Reject", "verb"), ("Relation", "noun"), ("Relationship", "noun"), ("Relative", "adjective"),
("Relatively", "adverb"), ("Relax", "verb"), ("Release", "noun"), ("Release", "verb"),
("Relevant", "adjective"), ("Reliable", "adjective"), ("Relief", "noun"), ("Relieve", "verb"),
("Religion", "noun"), ("Religious", "adjective"), ("Reluctant", "adjective"), ("Remain", "verb"),
("Remainder", "noun"), ("Remark", "noun"), ("Remarkable", "adjective"), ("Remember", "verb"),
("Remind", "verb"), ("Remote", "adjective"), ("Removal", "noun"), ("Remove", "verb"),
("Rent", "noun"), ("Rent", "verb"), ("Rental", "noun"), ("Repair", "verb"),
("Repeat", "verb"), ("Replace", "verb"), ("Replacement", "noun"), ("Reply", "noun"),
("Reply", "verb"), ("Report", "noun"), ("Report", "verb"), ("Reporter", "noun"),
("Represent", "verb"), ("Representation", "noun"), ("Representative", "noun"), ("Reproduce", "verb"),
("Reputation", "noun"), ("Request", "noun"), ("Request", "verb"), ("Require", "verb"),
("Requirement", "noun"), ("Rescue", "verb"), ("Research", "noun"), ("Research", "verb"),
("Reservation", "noun"), ("Reserve", "verb"), ("Resident", "noun"), ("Resist", "verb"),
("Resistance", "noun"), ("Resolution", "noun"), ("Resolve", "verb"), ("Resort", "noun"),
("Resource", "noun"), ("Respect", "noun"), ("Respect", "verb"), ("Responsible", "adjective"),
("Rest", "noun"), ("Rest", "verb"), ("Restaurant", "noun"), ("Restore", "verb"),
("Restrict", "verb"), ("Restriction", "noun"), ("Result", "noun"), ("Resume", "verb"),
("Retail", "noun"), ("Retain", "verb"), ("Retire", "verb"), ("Retirement", "noun"),
("Return", "noun"), ("Return", "verb"), ("Reveal", "verb"), ("Revenge", "noun"),
("Revenue", "noun"), ("Reverse", "adjective"), ("Reverse", "noun"), ("Reverse", "verb"),
("Review", "noun"), ("Review", "verb"), ("Revolution", "noun"), ("Reward", "noun"),
("Reward", "verb"), ("Rhythm", "noun"), ("Rice", "noun"), ("Rich", "adjective"),
("Rid", "verb"), ("Ride", "noun"), ("Ride", "verb"), ("Rider", "noun"),
("Ridiculous", "adjective"), ("Rifle", "noun"), ("Right", "adjective"), ("Right", "noun"),
("Right", "adverb"), ("Right", "verb"), ("Ring", "noun"), ("Ring", "verb"),
("Rip", "verb"), ("Rise", "noun"), ("Rise", "verb"), ("Risk", "noun"),
("Risk", "verb"), ("Rite", "noun"), ("River", "noun"), ("Road", "noun"),
("Roar", "noun"), ("Roar", "verb"), ("Rob", "verb"), ("Rock", "noun"), ("Rocket", "noun"), ("Rocky", "adjective"), ("Rod", "noun"), ("Role", "noun"),
("Roll", "noun"), ("Roll", "verb"), ("Roman", "adjective"), ("Romance", "noun"),
("Romantic", "adjective"), ("Roof", "noun"), ("Room", "noun"), ("Root", "noun"),
("Rope", "noun"), ("Rough", "adjective"), ("Roughly", "adverb"), ("Round", "adjective"),
("Round", "noun"), ("Round", "verb"), ("Route", "noun"), ("Routine", "noun"),
("Row", "noun"), ("Row", "verb"), ("Royal", "adjective"), ("Rub", "verb"),
("Rubber", "noun"), ("Rude", "adjective"), ("Ruin", "noun"), ("Ruin", "verb"),
("Rule", "noun"), ("Rule", "verb"), ("Ruler", "noun"), ("Run", "noun"),
("Run", "verb"), ("Rural", "adjective"), ("Rush", "noun"), ("Rush", "verb"),
("Russian", "adjective"), ("Sack", "noun"), ("Sack", "verb"), ("Sacred", "adjective"),
("Sad", "adjective"), ("Safe", "adjective"), ("Safety", "noun"), ("Sail", "noun"),
("Sail", "verb"), ("Sailing", "noun"), ("Sailor", "noun"), ("Saint", "noun"),
("Salary", "noun"), ("Sale", "noun"), ("Salt", "noun"), ("Same", "adjective"),
("Sample", "noun"), ("Sample", "verb"), ("Sanction", "noun"), ("Sanction", "verb"),
("Sand", "noun"), ("Satisfaction", "noun"), ("Satisfactory", "adjective"), ("Satisfy", "verb"),
("Saturday", "noun"), ("Sauce", "noun"), ("Save", "verb"), ("Saving", "noun"),
("Say", "verb"), ("Scale", "noun"), ("Scale", "verb"), ("Scan", "verb"),
("Scandal", "noun"), ("Scared", "adjective"), ("Scary", "adjective"), ("Scene", "noun"),
("Scent", "noun"), ("Schedule", "noun"), ("Scheme", "noun"), ("Scholar", "noun"),
("Scholarship", "noun"), ("School", "noun"), ("Science", "noun"), ("Scientific", "adjective"),
("Scientist", "noun"), ("Scissors", "noun"), ("Score", "noun"), ("Score", "verb"),
("Scrap", "noun"), ("Scratch", "verb"), ("Scream", "noun"), ("Scream", "verb"),
("Screen", "noun"), ("Screen", "verb"), ("Screw", "noun"), ("Screw", "verb"),
("Script", "noun"), ("Sea", "noun"), ("Seal", "noun"), ("Seal", "verb"),
("Search", "noun"), ("Search", "verb"), ("Season", "noun"), ("Seat", "noun"),
("Second", "adjective"), ("Second", "noun"), ("Secondary", "adjective"), ("Secret", "adjective"),
("Secret", "noun"), ("Secretary", "noun"), ("Section", "noun"), ("Sector", "noun"),
("Secure", "adjective"), ("Secure", "verb"), ("Security", "noun"), ("Seed", "noun"), ("Seek", "verb"), ("Seem", "verb"), ("Segment", "noun"),
("Select", "verb"), ("Selection", "noun"), ("Self", "noun"), ("Sell", "verb"),
("Senate", "noun"), ("Senator", "noun"), ("Send", "verb"), ("Senior", "adjective"),
("Sense", "noun"), ("Sensitive", "adjective"), ("Sentence", "noun"), ("Separate", "adjective"),
("Separate", "verb"), ("Separation", "noun"), ("September", "noun"), ("Sequence", "noun"),
("Series", "noun"), ("Serious", "adjective"), ("Seriously", "adverb"), ("Serve", "verb"),
("Service", "noun"), ("Session", "noun"), ("Set", "noun"), ("Set", "verb"),
("Setting", "noun"), ("Settle", "verb"), ("Settlement", "noun"), ("Seven", "noun"),
("Seventeen", "noun"), ("Seventh", "adjective"), ("Seventy", "noun"), ("Several", "determiner"),
("Severe", "adjective"), ("Sex", "noun"), ("Sexual", "adjective"), ("Shade", "noun"),
("Shadow", "noun"), ("Shake", "verb"), ("Shall", "modal verb"), ("Shame", "noun"),
("Shape", "noun"), ("Shape", "verb"), ("Share", "noun"), ("Share", "verb"),
("Sharp", "adjective"), ("Sharply", "adverb"), ("Shatter", "verb"), ("She", "pronoun"),
("Sheep", "noun"), ("Sheet", "noun"), ("Shelf", "noun"), ("Shell", "noun"),
("Shelter", "noun"), ("Shift", "noun"), ("Shift", "verb"), ("Shine", "verb"),
("Shiny", "adjective"), ("Ship", "noun"), ("Shirt", "noun"), ("Shock", "noun"),
("Shock", "verb"), ("Shoe", "noun"), ("Shoot", "verb"), ("Shop", "noun"),
("Shop", "verb"), ("Shopping", "noun"), ("Short", "adjective"), ("Shortly", "adverb"),
("Shot", "noun"), ("Should", "modal verb"), ("Shoulder", "noun"), ("Shout", "verb"),
("Show", "noun"), ("Show", "verb"), ("Shower", "noun"), ("Shrink", "verb"),
("Shut", "verb"), ("Shy", "adjective"), ("Sick", "adjective"), ("Side", "noun"),
("Sight", "noun"), ("Sign", "noun"), ("Sign", "verb"), ("Signal", "noun"),
("Signature", "noun"), ("Significant", "adjective"), ("Significantly", "adverb"), ("Silence", "noun"),
("Silent", "adjective"), ("Silk", "noun"), ("Silly", "adjective"), ("Silver", "noun"),
("Similar", "adjective"), ("Similarly", "adverb"), ("Simple", "adjective"), ("Simply", "adverb"),
("Sin", "noun"), ("Since", "preposition"), ("Sing", "verb"), ("Singer", "noun"),
("Single", "adjective"), ("Sink", "noun"), ("Sink", "verb"), ("Sister", "noun"),
("Sit", "verb"), ("Site", "noun"), ("Situation", "noun"), ("Six", "noun"), ("Sixteen", "noun"), ("Sixth", "adjective"), ("Sixty", "noun"),
("Size", "noun"), ("Skill", "noun"), ("Skin", "noun"), ("Sky", "noun"),
("Sleep", "noun"), ("Sleep", "verb"), ("Slightly", "adverb"), ("Slip", "noun"),
("Slip", "verb"), ("Slow", "adjective"), ("Slowly", "adverb"), ("Small", "adjective"),
("Smart", "adjective"), ("Smell", "noun"), ("Smell", "verb"), ("Smile", "noun"),
("Smile", "verb"), ("Smoke", "noun"), ("Smoke", "verb"), ("Smoking", "noun"),
("Smooth", "adjective"), ("Snake", "noun"), ("Snap", "verb"), ("Snow", "noun"),
("So", "conjunction"), ("Soap", "noun"), ("Social", "adjective"), ("Society", "noun"),
("Soft", "adjective"), ("Softly", "adverb"), ("Software", "noun"), ("Soil", "noun"),
("Soldier", "noun"), ("Solid", "adjective"), ("Solution", "noun"), ("Solve", "verb"),
("Some", "determiner"), ("Somebody", "pronoun"), ("Somehow", "adverb"), ("Someone", "pronoun"),
("Something", "pronoun"), ("Sometimes", "adverb"), ("Somewhat", "adverb"), ("Somewhere", "adverb"),
("Son", "noun"), ("Song", "noun"), ("Soon", "adverb"), ("Soothe", "verb"),
("Sophisticated", "adjective"), ("Sore", "adjective"), ("Sorry", "adjective"), ("Sort", "noun"),
("Sort", "verb"), ("Soul", "noun"), ("Sound", "noun"), ("Sound", "verb"),
("Soup", "noun"), ("Source", "noun"), ("South", "noun"), ("Southern", "adjective"),
("Sovereignty", "noun"), ("Space", "noun"), ("Spacious", "adjective"), ("Spain", "noun"),
("Spam", "noun"), ("Span", "noun"), ("Spanish", "adjective"), ("Spare", "adjective"),
("Spare", "verb"), ("Spatial", "adjective"), ("Speak", "verb"), ("Speaker", "noun"),
("Special", "adjective"), ("Specialist", "noun"), ("Specialize", "verb"), ("Specific", "adjective"),
("Specifically", "adverb"), ("Specify", "verb"), ("Specimen", "noun"), ("Spectacle", "noun"),
("Spectacular", "adjective"), ("Spectrum", "noun"), ("Speech", "noun"), ("Speed", "noun"),
("Spell", "verb"), ("Spelling", "noun"), ("Spending", "noun"), ("Sphere", "noun"),
("Spice", "noun"), ("Spider", "noun"), ("Spin", "verb"), ("Spirit", "noun"),
("Spiritual", "adjective"), ("Split", "verb"), ("Spokesman", "noun"), ("Sponsor", "noun"),
("Sponsor", "verb"), ("Spontaneous", "adjective"), ("Sport", "noun"), ("Spot", "noun"),
("Spot", "verb"), ("Spread", "verb"), ("Spring", "noun"), ("Square", "adjective"),
("Square", "adjective"), ("square", "adjective"),
("squeamish", "adjective"),
("stable", "adjective"),
("staid", "adjective"),
("stale", "adjective"),
("standard", "adjective"),
("stark", "adjective"),
("static", "adjective"),
("steadfast", "adjective"),
("steep", "adjective"),
("stern", "adjective"),
("sticky", "adjective"),
("stiff", "adjective"),
("still", "adjective"),
("stingy", "adjective"),
("stormy", "adjective"),
("stout", "adjective"),
("strange", "adjective"),
("strict", "adjective"),
("strident", "adjective"),
("strong", "adjective"),
("stuck", "adjective"),
("stupid", "adjective"),
("sturdy", "adjective"),
("subdued", "adjective"),
("submissive", "adjective"),
("substantial", "adjective"),
("subtle", "adjective"),
("successful", "adjective"),
("succinct", "adjective"),
("sudden", "adjective"),
("sufficient", "adjective"),
("sugary", "adjective"),
("sulky", "adjective"),
("sunny", "adjective"),
("superb", "adjective"),
("supreme", "adjective"),
("sure", "adjective"),
("surly", "adjective"),
("surprised", "adjective"),
("surreal", "adjective"),
("surrounding", "adjective"),
("suspect", "adjective"),
("suspicious", "adjective"),
("svelte", "adjective"),
("swanky", "adjective"),
("sweaty", "adjective"),
("sweet", "adjective"),
("sweltering", "adjective"),
("swift", "adjective"),
("sympathetic", "adjective"),
("tacit", "adjective"),
("tacky", "adjective"),
("tactful", "adjective"),
("tactless", "adjective"),
("talented", "adjective"),
("tall", "adjective"),
("tame", "adjective"),
("tan", "adjective"),
("tangible", "adjective"),
("tangy", "adjective"),
("tanned", "adjective"),
("tardy", "adjective"),
("tart", "adjective"),
("tasteful", "adjective"),
("tasteless", "adjective"),
("tasty", "adjective"),
("tattered", "adjective"),
("taut", "adjective"),
("taxing", "adjective"),
("tearful", "adjective"),
("tedious", "adjective"),
("teeming", "adjective"),
("temperate", "adjective"),
("temporary", "adjective"),
("tempting", "adjective"),
("ten", "adjective"),
("tender", "adjective"),
("tense", "adjective"),
("tenuous", "adjective"),
("terrible", "adjective"),
("terrific", "adjective"),
("terrified", "adjective"),
("terrifying", "adjective"),
("terse", "adjective"),
("tested", "adjective"),
("testy", "adjective"),
("thankful", "adjective"),
("that", "adjective"),
("these", "adjective"),
("thick", "adjective"),
("thin", "adjective"),
("thinkable", "adjective"),
("third", "adjective"),
("tactful", "adjective"),
("tangible", "adjective"),
("tantalizing", "adjective"),
("tedious", "adjective"),
("tenacious", "adjective"),
("tentative", "adjective"),
("terse", "adjective"),
("thriving", "adjective"),
("timid", "adjective"),
("torrid", "adjective"),
("tranquil", "adjective"),
("translucent", "adjective"),
("transparent", "adjective"),
("tremendous", "adjective"),
("triumphant", "adjective"),
("troubled", "adjective"),
("trustworthy", "adjective"), ("turbulent", "adjective"),
("ubiquitous", "adjective"),
("ultimate", "adjective"),
("unanimous", "adjective"),
("unassuming", "adjective"),
("unconventional", "adjective"),
("uncouth", "adjective"),
("understated", "adjective"),
("unequivocal", "adjective"),
("unflappable", "adjective"),
("unfettered", "adjective"),
("unforgiving", "adjective"),
("uninhibited", "adjective"),
("unique", "adjective"),
("unison", "noun"),
("universal", "adjective"),
("unkempt", "adjective"),
("unpredictable", "adjective"),
("unrequited", "adjective"),
("unscrupulous", "adjective"),
("unwavering", "adjective"),
("uplifting", "adjective"),
("urbane", "adjective"),
("vacant", "adjective"),
("vacillating", "adjective"),
("vague", "adjective"),
("venerated", "adjective"),
("vibrant", "adjective"),
("vicarious", "adjective"),
("vigilant", "adjective"),
("vigorous", "adjective"),
("vindictive", "adjective"),
("virtuous", "adjective"),
("vital", "adjective"),
("vivacious", "adjective"),
("vivid", "adjective"),
("vociferous", "adjective"),
("volatile", "adjective"),
("vulnerable", "adjective"),
("wanton", "adjective"),
("wary", "adjective"),
("whimsical", "adjective"),
("widespread", "adjective"),
("wistful", "adjective"),
("witty", "adjective"),
("wondrous", "adjective"),
("wrathful", "adjective"),
("xenophobic", "adjective"),
("yearning", "adjective"),
("youthful", "adjective"),
("zealous", "adjective")
};
  }
}